include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - android/**

formatter:
  page_width: 240

linter:
  rules:
    - prefer_single_quotes
    - require_trailing_commas
    - unawaited_futures
