include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - android/**

formatter:
  page_width: 240

linter:
  rules:
    directives_ordering: true
    prefer_single_quotes: true
    require_trailing_commas: true
    slash_for_doc_comments: false
    unawaited_futures: true
